id: P005437
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19615
  title: བདེ་ཆེན་རྒྱལ་མོའི་སྒྲུབ་གཞུང་གི་འགྲེལ་པ
  author: ''
  volumes:
    7c3fb03741774c3585a0723416d715db:
      image_group_id: I6066
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
