id: IC70CCCCE
legacy_id: P005437
ocr_import_info:
  bdrc_scan_id: W19615
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:32:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:29:25.822518+00:00'
last_modified: 2022-08-30 23:29:41.708163
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19615
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW19615
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་ཆེན་རྒྱལ་མོའི་སྒྲུབ་གཞུང་གི་འགྲེལ་པ།
  author: རྭ་སྟོན་ངག་དབང་བསྟན་འཛིན་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7255429997463484
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I6066:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6066
      total_pages: 220
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6066.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7255429997463484
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
