id: IC70CCCCE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:34:00+00:00'
last_modified: '2022-06-08T03:05:01.024006+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19615
  title: བདེ་ཆེན་རྒྱལ་མོའི་སྒྲུབ་གཞུང་གི་འགྲེལ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6550':
      image_group_id: I6066
      title: ''
      total_pages: 220
      order: 1
      base_file: 6550.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
